const { AWS_BUCKET_NAME } = require('../api/helpers/env');

module.exports = {
	SALT_ROUNDS: 10,
	MINLENGTH_ARRAYS: 1,
	MAXLENGTH_ARRAYS: 3,
	notificationTypes: {
		dashboard: 'dashboard',
		autoGenerated: 'autoGenerated',
	},
	paymentMethods: {
		cash: 'كاش',
		online: 'اونلاين',
	},
	orderStates: {
		cancelled: 'الغاء الطلب', // Only Users
		rejected: 'تم رفض الطلب', // Only Admins
		inCart: ' غير مكتمل',
		pending: 'قيد الانتظار', // in case: special Order
		processing: 'تم المعالجه',
		shipped: 'تم الشحن ',
		delivered: 'تم التوصيل',
	},
	passwordValidationOptions: {
		minLength: 8,
		minNumbers: 1,
		minUppercase: 1,
		minLowercase: 1,
		minSymbols: 1,
	},

	TargetCustomersEnum: {
		allUsers: 'جميع العملاء',
		hasInCompleteCart: 'العملاء أصحاب السلة الغير مكتملة',
		visitors: 'الزوار',
		someClients: 'اختيار بعض العملاء',
	},

	limitOfDocsInOnePage: 10,

	generalUrl: `https://${AWS_BUCKET_NAME}.s3.us-west-1.wasabisys.com/`,
	folders: {
		ads: 'ads/',
		notifications: 'notifications/',
		categories: 'categories/',
	},

	IMAGE_SIZE: 2 * 1024 * 1024, //2MB
	IMAGE_ALLOWEDEXTENTION: ['.jpg', '.jpeg', '.png'],
	userTypes: {
		admin: 'admin',
		user: 'user',
		visitor: 'visitor',
	},
	twilioVerificationStates: {
		pending: 'pending',
		approved: 'approved',
		canceled: 'canceled',
		max_attempts_reached: 'max_attempts_reached',
	},
	phone_E164FormatRegex: /^\+[1-9]\d{1,14}$/,
};
